### ISSUE TITLE
TODO: Enhancements

### ISSUE THREAD

**Issue by ganesh-k13** [ganesh-k13/titanium-silver#59]
There are various enhancements to be done, here are a few major/critical ones:

- [ ] A huge number of security vulnerabilities. Will be discussed only via DM [MAJOR]

- [ ] Frontend C-C++ bug, [MINOR]

- [ ] Create a .sh file for container-code execution. [MAJOR]

- [ ] From hardware perspective, many v-servers must be tried. [MINOR]

- [ ] Migration to Kubernetes. [IMP] [MINOR]

**Comment by Rahul-RB** [comment]
Could you create and add label `Docker` Enhancements. 

In fact, for each issue, we can create 3 labels to start with:
- `Docker`
- `Flask`
- `ReactJS`

This will help to filter out issues faster.

**Comment by parthvshah** [comment]
With respect to the "create a .sh file", do you wish for every container to use the same file but execute the command based on the language?

**Comment by ganesh-k13** [comment]
Hi Parath,
It's purely your choice but I would recommend a separate file per language to remove unnecessary coupling.
You can place them anywhere in the mounted folder of `codes`.
